# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 18:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20170714_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='id@email.com', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=9968465876, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Invalid mobile number', regex='^[789]\\d{9}$')]),
            preserve_default=False,
        ),
    ]
